# Server Configuration
server.port=8000

# Application Configuration
spring.application.name=apigateway-service

# ==========================================
# Spring Cloud Gateway MVC Routing Configuration
# ==========================================

# 1. Auth Service
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=https://backend-auth-service-gfqr.onrender.com
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

# 2. Chat Service
spring.cloud.gateway.mvc.routes[1].id=chat-service
spring.cloud.gateway.mvc.routes[1].uri=https://backend-chat-service.onrender.com
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/chat/**

# 3. AI Service
spring.cloud.gateway.mvc.routes[2].id=ai-service
spring.cloud.gateway.mvc.routes[2].uri=https://backend-ai-service-i7ru.onrender.com
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/docs/**, /api/ai/**

# ==========================================
# Eureka Client Configuration (Dev / Production)
# ==========================================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# ? ???? ?? ??? ?? ??? ??? IP/??? ?????.
eureka.client.service-url.defaultZone=http://43.203.242.84:8761/eureka/
eureka.instance.prefer-ip-address=true