# MySQL 8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/wemeetnow?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=wemtadm
spring.datasource.password=1234

jwt.secret=secretsecretsecretsecretsecretsecret