kakao.client_id=${KAKAO_CLIENT_ID:fe7e3ab97929873e8f9804f42a0a2397}
#kakao.redirect_uri: http://43.203.242.84:6112/callback
# kakao.redirect_uri=http://localhost:6112/api/auth/v1/kakao/callback
kakao.redirect_uri=${KAKAO_REDIRECT_URI:https://backend-auth-service-gfqr.onrender.com/api/auth/v1/kakao/callback}
# Mail ?? (Gmail ??)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_SEND:kyunghwanko1207@gmail.com}
# spring.mail.username=${EMAIL_USERNAME:wemeetnow@gmail.com}
spring.mail.password=${MAIL_PASSWORD:iiaevvdapwszjxrt}
# spring.mail.username=${EMAIL_PASSWORD:iiaevvdapwszjxrt}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}

# Redis ??
#spring.data.redis.host=${REDIS_HOST:localhost}
#spring.data.redis.port=${REDIS_PORT:6379}