kakao.client_id=fe7e3ab97929873e8f9804f42a0a2397
#kakao.redirect_uri: http://43.203.242.84:6112/callback
# kakao.redirect_uri=http://localhost:6112/api/auth/v1/kakao/callback
kakao.redirect_uri=https://backend-auth-service-gfqr.onrender.com/api/auth/v1/kakao/callback
# Mail ?? (Gmail ??)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kyunghwanko1207@gmail.com
# spring.mail.username=${EMAIL_USERNAME:wemeetnow@gmail.com}
spring.mail.password=iiaevvdapwszjxrt
# spring.mail.username=${EMAIL_PASSWORD:iiaevvdapwszjxrt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis ??
spring.data.redis.host=backend-auth-service-gfqr.onrender.com
spring.data.redis.port=6379