# MySQL 8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/wemeetnow?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
# spring.datasource.username=root
# spring.datasource.password=Qwe123!!

# Railway MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/wemeetnow?serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Qwe123!!}

# jwt.secret: secretsecretsecretsecretsecretsecret
jwt.secret=${JWT_SECRET:default_local_secret_key_at_least_32_bytes_long!!}