kakao.client_id=${KAKAO_CLIENT_ID:fe7e3ab97929873e8f9804f42a0a2397}
#kakao.redirect_uri: http://43.203.242.84:6112/callback
# kakao.redirect_uri=http://localhost:6112/api/auth/v1/kakao/callback
kakao.redirect_uri=${KAKAO_REDIRECT_URI:https://backend-auth-service-gfqr.onrender.com/api/auth/v1/kakao/callback}

resend.api.key=${RESEND_API_KEY:nullValue}
resend.api.url=${RESEND_API_URL:https://api.resend.com/emails}

# ??? ??
resend.sender.email=${RESEND_SENDER_EMAIL:no-reply@wemeetnow.kr}
resend.sender.name=${RESEND_SENDER_NAME:WeMeetTalk}