spring.application.name=service-discovery
server.port=8761

# ? ??: ?? ?? ??? IP ?? ?? ????? ?????.
eureka.instance.hostname=43.203.242.84

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ? defaultZone ??? ???? ??? ? ?? ?????(?? IP) ???? ?????.
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# ??????? ????? ?? IP ?? ???? ????? ?? (???? ?? ??? ??)
eureka.instance.prefer-ip-address=true

eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.response-cache-update-interval-ms=5000

management.endpoints.web.exposure.include=*