# Render PostgreSQL (Local Development)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-dasaa4h7lnhs738atgk0-a.singapore-postgres.render.com:5432/wemeetnow_wr58
spring.datasource.username=wmtadm
spring.datasource.password=RwPWtcqq2m0qHgNcAa2SBUccd0Z749uO

# Connection Pool Settings (HikariCP)
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

jwt.secret=secretsecretsecretsecretsecretsecret
